CREATE TABLE IF NOT EXISTS "products_backup" (
    product_id TEXT PRIMARY KEY,
    supplier TEXT,
    url TEXT,
    title TEXT,
    sku TEXT,
    category_path TEXT,
    description TEXT,
    properties TEXT,
    images TEXT,
    price REAL,
    currency TEXT,
    availability TEXT,
    variants TEXT,
    raw TEXT,
    content_hash TEXT,
    first_seen_at TIMESTAMP,
    last_seen_at TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "products_backup_v2"
                     (product_id TEXT PRIMARY KEY,
                      supplier TEXT,
                      url TEXT,
                      url_clean TEXT,
                      title TEXT,
                      sku TEXT,
                      category_path TEXT,
                      description TEXT,
                      properties TEXT,
                      images TEXT,
                      price REAL,
                      currency TEXT,
                      availability TEXT,
                      variants TEXT,
                      raw TEXT,
                      content_hash TEXT,
                      first_seen_at TIMESTAMP,
                      last_seen_at TIMESTAMP);
CREATE INDEX idx_url_clean ON "products_backup_v2"(url_clean);
CREATE INDEX idx_supplier ON "products_backup_v2"(supplier);
CREATE TABLE products
                 (catalog_id TEXT PRIMARY KEY,
                  product_id TEXT,
                  supplier_slug TEXT,
                  sku_clean TEXT,
                  supplier TEXT,
                  url TEXT,
                  url_clean TEXT,
                  title TEXT,
                  sku TEXT,
                  category_path TEXT,
                  description TEXT,
                  properties TEXT,
                  images TEXT,
                  price REAL,
                  currency TEXT,
                  availability TEXT,
                  variants TEXT,
                  raw TEXT,
                  content_hash TEXT,
                  first_seen_at TIMESTAMP,
                  last_seen_at TIMESTAMP, cloudinary_images TEXT);
CREATE INDEX idx_catalog_lookup ON products(supplier_slug, sku_clean);
